### ISSUE TITLE
uh oh blocked

### ISSUE THREAD

**Issue by Vulsez** [3kh0/ext-remover#19]
chrome web store is blocked chrome webstorex is blocked too i tried removing s from https but its just blank page

**Comment by nicolasog12** [comment]
Then I don't think you can do it - hopefully a  new method comes out

**Comment by 3kh0** [comment]
try https://chrome.google.com/webstoreAHHHH

**Comment by nicolasog12** [comment]
> try https://chrome.google.com/webstoreAHHHH

He means the domain is blocked.

**Comment by Vulsez** [comment]
Anything webstore related is blocked

**Comment by raventhecrabraver** [comment]
> Anything webstore related is blocked

check the website without modifying anything

**Comment by raventhecrabraver** [comment]
as in chrome.google.com/webstore

**Comment by Vulsez** [comment]
Yes chrome.google.com/webstore is blocked
