### ISSUE TITLE
New problem

### ISSUE THREAD

**Issue by Hackerboykid** [3kh0/ext-remover#22]
I have been using this for a while then One day I turned it on and it automatically set them to off but when I checked the extensions, they were still on, and now it won't let me turn them off, it turns blue and grey but doesn't actually work.

**Comment by Hackerboykid** [comment]
My school has  chrome://extensions blocked, the only site that works is https://chrome.google.com/webstore.

**Comment by Hackerboykid** [comment]
Tank you ill do that right now. this is off topic, but are you still in school age?

**Comment by 3kh0** [comment]
yes i still in school

**Comment by Hackerboykid** [comment]
Lol, I just finished a test

**Comment by Hackerboykid** [comment]
Wait were do I right click?

**Comment by 3kh0** [comment]
On the extension icon

**Comment by Hackerboykid** [comment]
ok im pretty sure im stupid, so please take a screen shot on you right clicking it. go here ----> 
[https://chrome.google.com/webstore/detail/netsweeper-workstation-ag/gehcmbonedocjpdjfemeklocmmpedmoj](url)

**Comment by Hackerboykid** [comment]
sorry

**Comment by 3kh0** [comment]
`gehcmbonedocjpdjfemeklocmmpedmoj` is the id

**Comment by Hackerboykid** [comment]
wow thanks
