### ISSUE TITLE
an idea

### ISSUE THREAD

**Issue by videoconsole** [3kh0/ext-remover#23]
is there i way for force DOWNLOAD an extension using the id or something because that would be the best

**Comment by 3kh0** [comment]
you can download the crx file just by going to a website like https://www.crx4chrome.com/ and looking up the extension but chrome will reject the crx because it not allowed by admin

**Comment by videoconsole** [comment]
so is there any way to force download an extension? i think some websites have a way to download an extension from their own website and not chrome web store.

**Comment by 3kh0** [comment]
nope, managed chromebooks check the crx file, those website download the crx and since the browser is not managed, chrome installs in (only if you have dev mode on)

**Comment by videoconsole** [comment]
so is there a way to force turn on dev mode or trick it into thinking dev mode is on a just enough time for it to download it?

**Comment by 3kh0** [comment]
nope

**Comment by videoconsole** [comment]
bruh sad

**Comment by videoconsole** [comment]
wait
![image](https://user-images.githubusercontent.com/75755629/193063922-3b35b2bf-b869-483e-9f70-3c2db3b5b9a4.png)

**Comment by videoconsole** [comment]
i could not do this before
![image](https://user-images.githubusercontent.com/75755629/193064833-329485c3-6497-4144-a33b-53cad96a354d.png)

**Comment by videoconsole** [comment]
ok nvm
![image](https://user-images.githubusercontent.com/75755629/193065222-b1d33d96-9417-46f3-85ad-01b523c72123.png)

**Comment by Aka-unblock** [comment]
> wait ![image](https://user-images.githubusercontent.com/75755629/193063922-3b35b2bf-b869-483e-9f70-3c2db3b5b9a4.png)

Try <a href="https://github.com/3kh0/ext-remover">Extension Launcher</a>
