### ISSUE TITLE
Its not responding at all

### ISSUE THREAD

**Issue by Mqthagod** [3kh0/ext-remover#24]
I did all the steps but nothing happens I'm at the webstorex website but that's it

**Comment by Mqthagod** [comment]
(about:blank#blocked) is the most that happens I tried to turn off 'about blank' and it didn't work

**Comment by raventhecrabraver** [comment]
i think the only working method now is ingot. gui.js has been patched.

**Comment by 3kh0** [comment]
try ingot

**Comment by LucRtheL** [comment]
Gui.js got patched. I was watching youtube using gui.js and all of the extensions I had disabled just reappeared. Ingot is the new norm.

**Comment by 3kh0** [comment]
pog
