### ISSUE TITLE
blocked

### ISSUE THREAD

**Issue by CheesyPoofs3** [3kh0/ext-remover#8]
wont work

**Comment by 3kh0** [comment]
Can you provide more context and/or screenshots?

**Comment by Aspaceman527** [comment]
![image](https://user-images.githubusercontent.com/92396467/191997991-f74c7bdc-eb0a-4bfe-ab92-7e848b66a728.png)

**Comment by Aspaceman527** [comment]
this pulls up for me

**Comment by 3kh0** [comment]
That is a hard block, can you try adding anything to the URL or downgrading to HTTP?

**Comment by CheesyPoofs3** [comment]
When i try to use it my bookmarklet does nothing any work around because all of my bookmarklets don't work but they worked before

**Comment by 3kh0** [comment]
Send your chrome://policy json file

**Comment by phillipbruh** [comment]
you dont have to use webstore x you can use chrome.google.com/webstore or  chrome.google.com/webstoresdassdlasndkjashdjahsdkhauiskdkhauk
