### ISSUE TITLE
you can disable issues

### ISSUE THREAD

**Issue by bloohacked** [3kh0/ext-remover#983]
do it

**Comment by myschoolisass** [comment]
what's the point of making a github issue just to ask to disable issues?

**Comment by AshtonDavies** [comment]
Only people creating new issues are the ones telling him to disable issues.

**Comment by BroJac5246** [comment]
> what's the point of making a github issue just to ask to disable issues? 

What's the point of a lot of stuff kids do? 

Yes, I do agree it's pointless, though. @3kh0 should just create a GitHub action that automatically closes opened issues.

**Comment by AshtonDavies** [comment]
I think he should allow collaborators to manage discussions and issues again so they don't have to keep getting bloated up by some users.

**Comment by 3kh0** [comment]
The problem with issues is that they can get annoying and bloated, I am open to allowing more issues, but it causes headaches

**Comment by AshtonDavies** [comment]
Sorry, what I meant is marking answers and deleting/editing posts, that permission.

**Comment by 3kh0** [comment]
Yes, I can definitely add other people as maintainers so they can manage discussions. I will be sure to add you. @AshtonDavies

**Comment by AshtonDavies** [comment]
Okay, thank you.

**Comment by Possumxkings** [comment]
PLEASE STOP MSGING ME I SWEAR TO ALL MIGHTY GODS JUTS STOP SPAMMING ME I
DONT CARE FOR ANY OF YOU CONVOS TAKE ME OUT OF THE GROUP FERAL JUST STOP
TALKING TO ME GOD
